### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ahmetb** [dellert/autocompleteajax#1]
Hey thanks for separating this code into its own repo. Finally we can evolve it independently!

But not having a license file prevents me from using it. Would you consider adding an appropriate license? Thanks!

**Comment by dellert** [comment]
@ahmetb add MIT license like in materializecss repo

**Comment by ahmetb** [comment]
@dellert thanks! I must kindly turn down your invite to be a contributor. I am not proficient enough in JavaScript or other front-end technologies to contribute in a meaningful way. However I will send pull requests and open issues, maybe other people will pick it up.

**Comment by dellert** [comment]
@ahmetb OK
