### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by younas-bangash** [dellert/autocompleteajax#7]
I was not able to understand where should we put the URL and I want to pass parameters in that URL so how should I pass that You did not explain properly for a beginner 

Let suppose my URL is https://abc.com/apis/get.php
```

<input id="street"
         type="text"
         autocomplete="off"
         name="street"
         data-url="/ajax/url-get-data"
         placeholder="Phone Number"
         class="js-street-select">
  <input type="hidden" class="autocomplete-id" name="autocomplete-id" value="">

```

```
var $street_select = $('.js-street-select');
    var $street_preloader = $('.js-street-preloader');
    var initial_address;
function getStreetAutocompleteObject(phoneNumber) {
    return {
        ajax: {
            url: $street_select.attr('data-url'),
            method: 'post',
            dataType: 'json',
            beforeSend: function () {
                if (!$street_preloader.hasClass('active')) {
                    $street_preloader.addClass('active');
                }
            },
            error: null
        },
        callback: function (res) {
            if ($street_preloader.hasClass('active')) {
                $street_preloader.removeClass('active');
            }
        },
        minLength: 5,
        delay: 200
    };
}
var value = document.getElementById('street').value;
$street_select.autocompleteajax(getStreetAutocompleteObject(value));
```

**Comment by fsher** [comment]
Hey, @younas-bangash!

If you are using a custom autocomplete from the example, I recommend adding to the ajax settings the 'data' option.
```
ajax: {
    url: $street_select.attr('data-url'),
    method: 'post',
    data: {
        phone: phoneNumber
    },
    dataType: 'json',
    beforeSend: function () {
        if (!$street_preloader.hasClass('active')) {
            $street_preloader.addClass('active');
        }
    },
    error: null
}
```

Did I understand your question correctly?
Usually it grabs the data from the input, so you should be passing it, if you are making your autocomplete custom.

Hope it helps!

**Comment by dellert** [comment]
what parameters you wanna pass to url? POST or GET? Get params sets to your data-url input attribute, POST sets in jquery ajax method with data attribute. Like post by @fsher

**Comment by dellert** [comment]
autocomplete takes options

` 
var defaults = {
        data: {},
        ajax: {},
        callback: null,
        delay: null,
        minLength: 2,
        autocomplete_id: null,
        input_name: null
    };
`

you can set ajax data in **ajax** option

**Comment by younas-bangash** [comment]
Where i should set the URL https://abc.com/apis/get.php ? I am confuse that where should i place my URL from which i am getting the data

**Comment by dellert** [comment]
Here
[http://joxi.ru/l2ZVGRgSwYvpY2](url=http://joxi.ru/l2ZVGRgSwYvpY2)

**Comment by younas-bangash** [comment]
No it's not working

**Comment by dellert** [comment]
Is ajax request firing?

**Comment by younas-bangash** [comment]
Yes it is but it does not sending the parameters and also give erro in cosole `Cannot read property 'toLowerCase' of undefined`

**Comment by dellert** [comment]
Can you show your code? How you set params?

**Comment by younas-bangash** [comment]
`<script src="js/autocompleteajax.js"></script>`     

  ```
<div class="input-field col s12">
  <div style="position: relative">
      <div class="preloader-wrapper small js-street-preloader" style="width: 20px; height: 20px; position: absolute; right: 0; margin-top: 15px">
          <div class="spinner-layer spinner-blue-only">
              <div class="circle-clipper left">
                  <div class="circle"></div>
              </div><div class="gap-patch">
                  <div class="circle"></div>
              </div><div class="circle-clipper right">
                  <div class="circle"></div>
              </div>
          </div>
      </div>
  </div>
  <input id="street"
         type="text"
         autocomplete="off"
         name="street"
         data-url="apis/search_customer.php"
         placeholder="Phone Number"
         class="js-street-select">
  <input type="hidden" class="autocomplete-id" name="autocomplete-id" value="">
</div>
```

```

var $street_select = $('.js-street-select');
var $street_preloader = $('.js-street-preloader');
var initial_address;
var value = document.getElementById('street').value;
$street_select.autocompleteajax(getStreetAutocompleteObject(value));

function getStreetAutocompleteObject(phone_number){
  return {
        ajax: {
            url: $street_select.attr('data-url'),
            method: 'post',
            data: {
                 phone_number: phone_number
            },
            dataType: 'json',
            beforeSend: function () {
                if (!$street_preloader.hasClass('active')) {
                    $street_preloader.addClass('active');
                }
            },
            error: null
        },
        callback: function (res) {
            if ($street_preloader.hasClass('active')) {
                $street_preloader.removeClass('active');
            }
        },
        minLength: 2,
        delay: 200
    }; 
}
```

**Comment by fsher** [comment]
https://abc.com/apis/get.php
Is this the URL you are trying to send the request to? Or is it the one in the data-url attribute?

**Comment by dellert** [comment]
No need set param to getStreetAutocompleteObject() function. Value from input parsed by plugin

**Comment by younas-bangash** [comment]
I can not post the original URL due to security reason but the file is returning the JSON data my file is on server in apis folderand its name is search_customer.php. SO tell me how to send parameters

**Comment by younas-bangash** [comment]
I successfully add the parameters in the` autocompleteajax.js` file but I am receiving the following error now and the result is not displaying in the dopdown

```
autocompleteajax.js:110 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at String.<anonymous> (autocompleteajax.js:110)
    at Function.each (jquery-2.1.1.min.js:2)
    at HTMLInputElement.<anonymous> (autocompleteajax.js:109)
    at HTMLInputElement.dispatch (jquery-2.1.1.min.js:3)
    at HTMLInputElement.r.handle (jquery-2.1.1.min.js:3)
```

**Comment by dellert** [comment]
There is no toLowerCase method on 110 line
https://github.com/dellert/autocompleteajax/blob/master/autocompleteajax.js#L110
:)

Are you sure, that you have using last verion?:)

**Comment by younas-bangash** [comment]
I do not know what is happining but I paste the error which I am facing and I am using the latest version I think I should use another library but I do not know how to solve that issue

**Comment by dellert** [comment]
I think, you make smth wrong. I cannot reproduce same error

**Comment by younas-bangash** [comment]
But why it show error in the autocompleteajax.js file ?

**Comment by younas-bangash** [comment]
![image](https://user-images.githubusercontent.com/4440531/30271839-dfaf8360-9702-11e7-9f73-db1167d6719f.png)

**Comment by dellert** [comment]
https://jsfiddle.net/gayvryLq/1/

**Comment by younas-bangash** [comment]
Yes doing the like that but still facing the issue

**Comment by younas-bangash** [comment]
![image](https://user-images.githubusercontent.com/4440531/30272801-48f6d0b8-9707-11e7-900c-a6fdad7d4824.png)

**Comment by dellert** [comment]
So, is your response from server an array of objects? Can you show response example?

**Comment by dellert** [comment]
Updated readme

**Comment by younas-bangash** [comment]
It can be multipes items
```
[
{
customer_id: "5",
customer_name: "Customer2",
customer_email: "test@test.com",
customer_phone: "971"
}
]
```

**Comment by dellert** [comment]
if you look in source by materialize (and this extension too), you'll see, that response **must** include just _id_ and _value_ params and **may** include _image_ param

**Comment by younas-bangash** [comment]
@dellert I update my json output as below but still I am receiving the issue  `Uncaught TypeError: Cannot read property 'toLowerCase' of undefined`

```
{ data: [{
     id: "5",
    value: "971"
}],
status: "200"
}
```

**Comment by younas-bangash** [comment]
@dellert  if you see the below image I am receiving the array but when I get specific value than it is undefined due to which I am facing that issue


![image](https://user-images.githubusercontent.com/4440531/30274613-4751e7d6-970f-11e7-9a3d-eed1f5cdf92d.png)

**Comment by dellert** [comment]
![11-09-2017 13-20-38](https://user-images.githubusercontent.com/5858057/30274693-30dd1d16-9707-11e7-8c51-cda6f51e4391.png)

**Comment by younas-bangash** [comment]
I did not know what are you trying to say but I will search for other tools thanks for your help

**Comment by younas-bangash** [comment]
![image](https://user-images.githubusercontent.com/4440531/30275968-4e107cea-9714-11e7-855e-dbdd598e8e6f.png)

**Comment by younas-bangash** [comment]
@dellert  thanks for closing the issue without solving it

**Comment by younas-bangash** [comment]
@fsher   @free6k  @m4k5imG I will be very thankful if you can figure it out the issue because there is nothing in my page just input box which i am typing Otherwise I will share you my code and Below is the response which i receive  but still i receive the error

```
autocompleteajax.js:112 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Array.<anonymous> (autocompleteajax.js:112)
    at Function.each (jquery-2.1.1.min.js:2)
    at HTMLInputElement.<anonymous> (autocompleteajax.js:109)
    at HTMLInputElement.dispatch (jquery-2.1.1.min.js:3)
    at HTMLInputElement.r.handle (jquery-2.1.1.min.js:3)
```


![image](https://user-images.githubusercontent.com/4440531/30276873-4381deba-9717-11e7-94c0-b21d01553bac.png)

**Comment by younas-bangash** [comment]
Thanks you guys I do not know issue but I solve the issue by removing the below lines from autocompleteajax.js and placed inside the success: function of ajax


```
if (val !== '') {
                (data) && $.each(data, function(i, value) {
                    console.log(data);
                    console.log("Value : "+ value.value);
                    if (value.value.toLowerCase().indexOf(val) !== -1 &&
                        value.value.toLowerCase() !== val) {
                        var autocompleteOption = $('<li data-id="'+ value.id +'"></li>');

                        if(!!value.image) {
                            autocompleteOption.append('<img src="'+ value.image +'" class="right circle"><span>'+ value.value +'</span>');
                        } else {
                            autocompleteOption.append('<span>'+ value.value +'</span>');
                        }

                        $autocomplete.append(autocompleteOption);
                        highlight(val, autocompleteOption);
                    }
                });
```

**Comment by astarrh** [comment]
I had the same issue. I think I was following the data structure correctly by providing one success object and the results in a list of dictionaries. However, the code was not reaching my results. I solved it by changing the code:

```
if (val !== '') {    
    var results = data.data;
    (results) && $.each(results, function(i, value) {
        ...
    }
```
Also, I had to cut a piece out to get my input working as well. I put both changes in my fork, for anyone else's reference.

Wonderful tool, btw. Many thanks for putting it together!

**Comment by dellert** [comment]
> I put both changes in my fork

@astarrh your pull request has just edited reame file

**Comment by astarrh** [comment]
Sorry, I had not made a pull request... simply a fork. I just submitted a pull request with my modifications.

**Comment by dellert** [comment]
@astarrh good!

**Comment by nileshbacancy** [comment]
There should not be remove any code  from existing autocomplete js file but you need to just keep one key from server side which name should be "value". that's it.  
i.e. { value: 'server value', data: 'ALL' }
It's working for me.

**Comment by tanzito** [comment]
hola a todos, normalmente no se comentar, pero esta vez si debido a que yo también tuve el mismo problema,
yo estaba trabajando con una plantilla que tenia agregado la librería de jquery.autocomplete.init.js
lo que ise fue quitarla, no encontré una solución a ello , pero el problema que encontré se encuentra en esta librería, si alguien pudiera resolverlo seria de gran ayuda del por que dicha librería trae ese problema .. gracias ..!

**Comment by dellert** [comment]
> hola a todos, normalmente no se comentar, pero esta vez si debido a que yo también tuve el mismo problema,
> yo estaba trabajando con una plantilla que tenia agregado la librería de jquery.autocomplete.init.js
> lo que ise fue quitarla, no encontré una solución a ello , pero el problema que encontré se encuentra en esta librería, si alguien pudiera resolverlo seria de gran ayuda del por que dicha librería trae ese problema .. gracias ..!

White on english please
